"""
The model parameters.
"""


from PyQt5.QtWidgets import QGraphicsItem


# === DEBUG ===
DEBUG_EFFECT_SNOW = False
DEBUG_TUPLE_NODE_SCALE = False
DEBUG_VIEW_CHANGE_SCALE = False
DEBUG_DRAW_PIPE = False
DEBUG_TEXT_CHANGED = False
DEBUG_PYTHON_SYNTAXHIGHTLIGHTER = False
DEBUG_RICHTEXT = False
DEBUG_CUT_LINE = False
DEBUG_COLLIDING = False
DEBUG_HISTORY = False
DEBUG_DESERIALIZE = False
DEBUG_FONT = False
DEBUG_FILE_SAVE = False
DEBUG_ATTRIBUTE_INDEX = False
DEBUG_MARKDOWN = True

# === DRAW STACK ORDER ===
Z_VAL_PIPE = 2
Z_VAL_PIPE_DONE = 4
Z_VAL_NODE = 3
Z_VAL_PORT = 3
Z_VAL_CUTLINE = 5
Z_VAL_CONTAINERS = 6

# === NODE ===
NODE_WIDTH = 150
NODE_HEIGHT = 70
NODE_LAYOUT_MARGINS = 5
NODE_ICON_SIZE = 24
NODE_SEL_COLOR = (255, 255, 255, 30)
NODE_SEL_BORDER_COLOR = (254, 207, 42, 255)

# === ITEM CACHE MODE ===
ITEM_CACHE_MODE = QGraphicsItem.DeviceCoordinateCache

# === NODE TYPE ===
INPUT_NODE_TYPE = 0
OUTPUT_NODE_TYPE = 1

# === DRAW LINE ===
MODE_NOOP = 1
MODE_PIPE_DRAG = 2
MODE_PIPE_CUT = 3
MODE_CONTAINER = 4

# === PIPE ===
PIPE_STATUS_NEW = 0
PIPE_STATUS_CHANGE = 1

# === PIPE START STATUS ===
INPUT_NODE_START = 0
OUTPUT_NODE_START = 1

# === COLLIDING ===
COLLIDING_ATTRIBUTE = 0
COLLIDING_PIPE = 1
COLLIDING_NONE = 2

# === PIPE MOVE ===
PIPE_FIRST = 0
PIPE_MOVEING = 1
PIPE_COMMON = 2
PIPE_UPDATE = 3

# === MOVE ===
down = 0
up = 1
left = 2
right = 3
